update volume out calc
ref-finance/ref-contracts pull request #8
Opened 2021-03-30 15:50 UTC by mehtaphysical

Isn't this supposed to update the `out_idx` volume instead?

2021-03-30 20:06 UTC, robert-zaremba commented
yeap. This unfortunately breaks the stats of currently running pools.

2021-03-30 20:06 UTC, robert-zaremba approved these changes

2021-03-31 05:51 UTC, ilblackdragon commented
Logic is that you keep track of volumes from each input side separately. You can either count volume in token A or in token B (independent if it was input or output for a trade), while still it's interesting how much each side contributed.

PS. I was reusing logic from mooniswap - https://github.com/1inch/mooniswap/blob/master/contracts/Mooniswap.sol#L260.

For UI this probably should be fetched from indexer long term, because to covert to $ the price at the moment of trade must be accounted for. Cumulative price on chain might be more important than having these volumes on chain.

2021-03-31 05:55 UTC, ilblackdragon requested changes
Logic is that you keep track of volumes from each input side separately. You can either count volume in token A or in token B (independent if it was input or output for a trade), while still it's interesting how much each side contributed.

PS. I was reusing logic from mooniswap - https://github.com/1inch/mooniswap/blob/master/contracts/Mooniswap.sol#L260.

For UI this probably should be fetched from indexer long term, because to covert to $ the price at the moment of trade must be accounted for. Cumulative price on chain might be more important than having these volumes on chain.

2021-03-31 06:30 UTC, closed without merging